"""convert varchar FK/id columns to uuid (safe, additive revision)

Revision ID: c4d2e6f0a9b1
Revises: 7f8e9d0c1b2a
Create Date: 2025-11-06 14:20:00.000000

This migration attempts to safely convert previously-created
`character varying` (varchar) columns used as UUIDs into proper
`uuid` columns in Postgres. It performs validation to ensure values
are valid UUID strings before altering the column types. It also
drops and recreates foreign key constraints as necessary.

NOTES / SAFETY:
- Run this on a copy of your DB first. If any value in the affected
  columns is not a valid UUID string the migration will raise and
  stop to avoid data corruption.
- This revision enables the `pgcrypto` extension if not present.
  If you prefer `uuid-ossp` change the CREATE EXTENSION line.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c4d2e6f0a9b1'
down_revision = '7f8e9d0c1b2a'
branch_labels = None
depends_on = None


def _drop_fk_constraints_for(table_name: str, column_name: str):
    # Drop any foreign key constraints that reference `table_name(column_name)`
    # We query information_schema for FK constraints that use the column and
    # then drop each one by name.
    sql = f"""
    DO $$
    DECLARE r RECORD;
    BEGIN
      FOR r IN
        SELECT tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND kcu.table_name = '{table_name}'
          AND kcu.column_name = '{column_name}';
      LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', '{table_name}', r.constraint_name);
      END LOOP;
    END$$;
    """
    return sql


def _add_fk(table_name: str, column_name: str, ref_table: str, ref_column: str, constraint_name: str = None):
    # Add a basic foreign key constraint. Default constraint name will be
    # autogenerated by Postgres if not provided.
    if constraint_name:
        return f"ALTER TABLE {table_name} ADD CONSTRAINT {constraint_name} FOREIGN KEY ({column_name}) REFERENCES {ref_table}({ref_column});"
    return f"ALTER TABLE {table_name} ADD FOREIGN KEY ({column_name}) REFERENCES {ref_table}({ref_column});"


def upgrade():
    bind = op.get_bind()

    # This migration is Postgres-specific (uses CREATE EXTENSION and TYPE uuid).
    # If running against a non-Postgres dialect (e.g., SQLite for tests), skip
    # the conversion to avoid syntax errors.
    if bind.dialect.name != "postgresql":
        # Alembic will still mark this revision as applied; we simply skip
        # the Postgres-specific work when running in SQLite or other DBs.
        print("Skipping UUID conversion migration: not running on PostgreSQL (dialect=%s)" % bind.dialect.name)
        return

    # 0) Ensure pgcrypto exists (used for gen_random_uuid) — change to uuid-ossp if preferred.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    # NOTE: The event and event_participant tables were created with UUID types
    # from the start in migration 7f8e9d0c1b2a, so there's nothing to convert.
    # This migration is a no-op for those tables. If you have OTHER tables that
    # were created with varchar UUID columns, add their conversion logic here.
    
    # Example: If user/item tables needed conversion from varchar to UUID, you would:
    # 1) Validate existing varchar values are valid UUIDs
    # 2) Drop FK constraints
    # 3) ALTER COLUMN ... TYPE uuid USING column::uuid
    # 4) Recreate FK constraints
    
    # Since event/event_participant are already UUID, no action needed.
    print("Event and event_participant tables already use native UUID types. No conversion needed.")


def downgrade():
    bind = op.get_bind()

    # Skip downgrade changes on non-Postgres dialects (no-op for SQLite etc.).
    if bind.dialect.name != "postgresql":
        print("Skipping UUID conversion downgrade: not running on PostgreSQL (dialect=%s)" % bind.dialect.name)
        return

    # Event/event_participant were created as UUID from the start, so downgrade is a no-op.
    print("Event and event_participant tables were created with UUID types. No downgrade needed.")
