"""convert varchar FK/id columns to uuid (safe, additive revision)

Revision ID: c4d2e6f0a9b1
Revises: 7f8e9d0c1b2a
Create Date: 2025-11-06 14:20:00.000000

This migration attempts to safely convert previously-created
`character varying` (varchar) columns used as UUIDs into proper
`uuid` columns in Postgres. It performs validation to ensure values
are valid UUID strings before altering the column types. It also
drops and recreates foreign key constraints as necessary.

NOTES / SAFETY:
- Run this on a copy of your DB first. If any value in the affected
  columns is not a valid UUID string the migration will raise and
  stop to avoid data corruption.
- This revision enables the `pgcrypto` extension if not present.
  If you prefer `uuid-ossp` change the CREATE EXTENSION line.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c4d2e6f0a9b1'
down_revision = '7f8e9d0c1b2a'
branch_labels = None
depends_on = None


def _drop_fk_constraints_for(table_name: str, column_name: str):
    # Drop any foreign key constraints that reference `table_name(column_name)`
    # We query information_schema for FK constraints that use the column and
    # then drop each one by name.
    sql = f"""
    DO $$
    DECLARE r RECORD;
    BEGIN
      FOR r IN
        SELECT tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND kcu.table_name = '{table_name}'
          AND kcu.column_name = '{column_name}';
      LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', '{table_name}', r.constraint_name);
      END LOOP;
    END$$;
    """
    return sql


def _add_fk(table_name: str, column_name: str, ref_table: str, ref_column: str, constraint_name: str = None):
    # Add a basic foreign key constraint. Default constraint name will be
    # autogenerated by Postgres if not provided.
    if constraint_name:
        return f"ALTER TABLE {table_name} ADD CONSTRAINT {constraint_name} FOREIGN KEY ({column_name}) REFERENCES {ref_table}({ref_column});"
    return f"ALTER TABLE {table_name} ADD FOREIGN KEY ({column_name}) REFERENCES {ref_table}({ref_column});"


def upgrade():
    bind = op.get_bind()

    # This migration is Postgres-specific (uses CREATE EXTENSION and TYPE uuid).
    # If running against a non-Postgres dialect (e.g., SQLite for tests), skip
    # the conversion to avoid syntax errors.
    if bind.dialect.name != "postgresql":
        # Alembic will still mark this revision as applied; we simply skip
        # the Postgres-specific work when running in SQLite or other DBs.
        print("Skipping UUID conversion migration: not running on PostgreSQL (dialect=%s)" % bind.dialect.name)
        return

    # 0) Ensure pgcrypto exists (used for gen_random_uuid) — change to uuid-ossp if preferred.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    # 1) Validate that existing values look like UUIDs. If any invalid
    # values are found we abort the migration to avoid corrupting data.
    validate_checks = [
        ("event", "id"),
        ("event", "owner_id"),
        ("event_participant", "id"),
        ("event_participant", "event_id"),
        ("event_participant", "user_id"),
    ]

    uuid_regex = r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'

    for table, column in validate_checks:
        op.execute(
            f"""
            DO $$
            DECLARE bad_count INTEGER;
            BEGIN
              SELECT COUNT(*) INTO bad_count FROM {table} WHERE {column} IS NOT NULL AND {column} !~ '{uuid_regex}';
              IF bad_count > 0 THEN
                RAISE EXCEPTION 'Migration aborted: % rows in {table}.{column} are not valid UUID strings', bad_count;
              END IF;
            END$$;
            """
        )

    # 2) Drop foreign key constraints that will interfere with type changes.
    op.execute(_drop_fk_constraints_for('event_participant', 'event_id'))
    op.execute(_drop_fk_constraints_for('event_participant', 'user_id'))
    op.execute(_drop_fk_constraints_for('event', 'owner_id'))

    # 3) Alter column types to uuid using a safe cast. We alter primary keys
    # and FK columns listed above. The USING ...::uuid cast assumes the
    # textual values are valid UUID strings (we validated earlier).
    op.execute("ALTER TABLE event ALTER COLUMN id TYPE uuid USING id::uuid;")
    op.execute("ALTER TABLE event ALTER COLUMN owner_id TYPE uuid USING owner_id::uuid;")

    op.execute("ALTER TABLE event_participant ALTER COLUMN id TYPE uuid USING id::uuid;")
    op.execute("ALTER TABLE event_participant ALTER COLUMN event_id TYPE uuid USING event_id::uuid;")
    op.execute("ALTER TABLE event_participant ALTER COLUMN user_id TYPE uuid USING user_id::uuid;")

    # 4) Recreate basic foreign key constraints with ON DELETE CASCADE.
    op.execute("ALTER TABLE event_participant ADD FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE;")
    op.execute("ALTER TABLE event_participant ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;")
    op.execute("ALTER TABLE event ADD FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;")


def downgrade():
    bind = op.get_bind()

    # Skip downgrade changes on non-Postgres dialects (no-op for SQLite etc.).
    if bind.dialect.name != "postgresql":
        print("Skipping UUID conversion downgrade: not running on PostgreSQL (dialect=%s)" % bind.dialect.name)
        return

    # Downgrade will attempt to cast uuid columns back to varchar(36).
    op.execute(_drop_fk_constraints_for('event_participant', 'event_id'))
    op.execute(_drop_fk_constraints_for('event_participant', 'user_id'))
    op.execute(_drop_fk_constraints_for('event', 'owner_id'))

    op.execute("ALTER TABLE event_participant ALTER COLUMN user_id TYPE varchar(36) USING user_id::text;")
    op.execute("ALTER TABLE event_participant ALTER COLUMN event_id TYPE varchar(36) USING event_id::text;")
    op.execute("ALTER TABLE event_participant ALTER COLUMN id TYPE varchar(36) USING id::text;")

    op.execute("ALTER TABLE event ALTER COLUMN owner_id TYPE varchar(36) USING owner_id::text;")
    op.execute("ALTER TABLE event ALTER COLUMN id TYPE varchar(36) USING id::text;")

    op.execute("ALTER TABLE event_participant ADD FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE;")
    op.execute("ALTER TABLE event_participant ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;")
    op.execute("ALTER TABLE event ADD FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;")
